# Generated by Django 5.1.7 on 2025-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_sociallink_sociallinks_portfolio_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_nu',
            field=models.IntegerField(default=0),
        ),
    ]
