# Generated by Django 5.1.7 on 2025-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_project_nu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_nu',
            field=models.IntegerField(),
        ),
    ]
