# Generated by Django 5.1.7 on 2025-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_about_name_remove_about_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='social_icon',
            field=models.ImageField(null=True, upload_to='About_icon/'),
        ),
    ]
