# Generated by Django 5.1.7 on 2025-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_sociallinks_social_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='social_icon',
            field=models.ImageField(blank=True, null=True, upload_to='About_icon/'),
        ),
    ]
