# Generated by Django 5.1.7 on 2025-03-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_sociallinks_social_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='home',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.home'),
            preserve_default=False,
        ),
    ]
