# Generated by Django 5.1.7 on 2025-03-15 17:39

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.models.rename_cv, validators=[portfolio.models.validate_cv_size]),
        ),
    ]
