# Generated by Django 5.1.7 on 2025-03-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
